// <auto-generated />
using System;
using ExchangePulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangePulse.Infrastructure.Migrations
{
    [DbContext(typeof(ExchangePulseDbContext))]
    [Migration("20260120174037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExchangePulse.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ExchangePulse.Domain.Entities.ExchangeMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Beta")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyVariation")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Drawdown")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Inflation")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LogReturn")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MovingAverage30d")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MovingAverage7d")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SharpeAnnual")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SharpeDaily")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("VaRCornishFisher95")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("VaREmpirical95")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Volatility30d")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeMetrics");
                });

            modelBuilder.Entity("ExchangePulse.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacroEvents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("ExchangePulse.Domain.Entities.ExchangeMetric", b =>
                {
                    b.HasOne("ExchangePulse.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ExchangePulse.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("ExchangePulse.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
